title: "Multi-objective Bayesian Optimization for Combustion CFD"
footer:
  text: NHR4CES Training - Numerical methods in combustion
  bold:
    - NHR4CES Training
author: Mohammed Elwardi Fadeli
time: Nov. 2024
logo:
  image: nhr-tu-logo.png
  scale: 0.6
base_url: https://foamscience.github.io/nhr-training-sandia-d-flame-presentation
thanks: THANK YOU for your attention!
